name: nahuali
favicon: null
layout_spectrum: 0.7090535366442055
typography_spectrum: 0.0955336291808635
title: otherworldly design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.421032176585868
  lightness: 0.026040828321129084
  saturation: 0.4636732100043446
  rhythmicContrast: 0.9560484942048788
purpose: []
